/**
 * Airtable OAuth 2.0 Client — "Sign in with Airtable"
 *
 * Implements the authorization-code flow for the Airtable OAuth 2.0 API.
 * The adapter contract (`supplier.interface.ts`) is unchanged: this client is
 * used only by the connect flow (authorize/callback routes) and by the
 * Airtable supplier adapter to present the user's token to the Airtable API.
 *
 * Reference: https://airtable.com/developers/web/guides/oauth-integrations
 *
 * Security boundaries:
 *   • Client secret never leaves the server (only sent to Airtable's token
 *     endpoint inside a POST body).
 *   • `state` is generated by the caller (route) and bound to the tenant+user;
 *     this client only echoes it back to the provider.
 *   • No logging of tokens or codes is performed here.
 */

export interface AirtableOAuthConfig {
  clientId: string;
  clientSecret: string;
  redirectUri: string;
}

export interface AirtableTokenResult {
  accessToken: string;
  refreshToken: string | null;
  expiresAt: Date;
  tokenType: string;
  scope: string;
}

export interface AirtableBaseSummary {
  id: string;
  name: string;
}

export interface AirtableTableSummary {
  id: string;
  name: string;
}

/** Phase-1 scopes: read records + discover the authorized base/table schema. */
export const AIRTABLE_SCOPES = [
  'data.records:read',
  'schema.bases:read',
] as const;

const AIRTABLE_AUTH_URL = 'https://airtable.com/oauth2/v1/authorize';
const AIRTABLE_TOKEN_URL = 'https://airtable.com/oauth2/v1/token';
const AIRTABLE_API_URL = 'https://api.airtable.com/v0';

type Fetcher = (input: string | URL, init?: RequestInit) => Promise<Response>;

function toTokenResult(data: {
  access_token?: string;
  refresh_token?: string | null;
  expires_in?: number;
  token_type?: string;
  scope?: string;
  error?: string;
  error_description?: string;
}): AirtableTokenResult {
  if (!data.access_token) {
    throw new Error(
      `Airtable token response missing access_token: ${data.error ?? 'unknown error'} ${data.error_description ?? ''}`,
    );
  }
  return {
    accessToken: data.access_token,
    refreshToken: data.refresh_token ?? null,
    expiresAt: new Date(Date.now() + (data.expires_in ?? 3600) * 1000),
    tokenType: data.token_type ?? 'Bearer',
    scope: data.scope ?? '',
  };
}

export class AirtableOAuthClient {
  private readonly config: AirtableOAuthConfig;
  private readonly fetcher: Fetcher;

  constructor(config: AirtableOAuthConfig, fetcher?: Fetcher) {
    this.config = config;
    this.fetcher =
      fetcher ??
      ((input: string | URL, init?: RequestInit) => fetch(input, init));
  }

  /**
   * Build the Airtable authorization URL the user is redirected to.
   * The `state` value is supplied by the route and MUST encode the tenant+user
   * so the callback can verify the response belongs to the initiating actor.
   */
  getAuthorizationUrl(
    state: string,
    scopes: readonly string[] = AIRTABLE_SCOPES,
  ): string {
    const url = new URL(AIRTABLE_AUTH_URL);
    url.searchParams.set('client_id', this.config.clientId);
    url.searchParams.set('redirect_uri', this.config.redirectUri);
    url.searchParams.set('response_type', 'code');
    url.searchParams.set('scope', scopes.join(' '));
    url.searchParams.set('state', state);
    return url.toString();
  }

  /** Exchange the authorization code for an access token (+ refresh token). */
  async exchangeCodeForToken(code: string): Promise<AirtableTokenResult> {
    const body = new URLSearchParams({
      grant_type: 'authorization_code',
      code,
      redirect_uri: this.config.redirectUri,
      client_id: this.config.clientId,
      client_secret: this.config.clientSecret,
    });

    const res = await this.fetcher(AIRTABLE_TOKEN_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: body.toString(),
    });

    if (!res.ok) {
      const text = await res.text();
      throw new Error(`Airtable token exchange failed (${res.status}): ${text}`);
    }

    return toTokenResult((await res.json()) as Parameters<typeof toTokenResult>[0]);
  }

  /** Refresh an expired access token using the stored refresh token. */
  async refreshAccessToken(refreshToken: string): Promise<AirtableTokenResult> {
    const body = new URLSearchParams({
      grant_type: 'refresh_token',
      refresh_token: refreshToken,
      client_id: this.config.clientId,
      client_secret: this.config.clientSecret,
    });

    const res = await this.fetcher(AIRTABLE_TOKEN_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: body.toString(),
    });

    if (!res.ok) {
      const text = await res.text();
      throw new Error(`Airtable token refresh failed (${res.status}): ${text}`);
    }

    return toTokenResult((await res.json()) as Parameters<typeof toTokenResult>[0]);
  }

  /** List bases the authorized user has granted to this integration. */
  async listBases(accessToken: string): Promise<AirtableBaseSummary[]> {
    const res = await this.fetcher(`${AIRTABLE_API_URL}/meta/bases`, {
      headers: { Authorization: `Bearer ${accessToken}` },
    });

    if (!res.ok) {
      const text = await res.text();
      throw new Error(`Airtable bases lookup failed (${res.status}): ${text}`);
    }

    const data = (await res.json()) as {
      bases?: Array<{ id?: string; name?: string }>;
    };
    return (data.bases ?? [])
      .filter((b) => b.id && b.name)
      .map((b) => ({ id: b.id as string, name: b.name as string }));
  }

  /** List tables inside a base (used to default the adapter's tableName). */
  async listTables(
    accessToken: string,
    baseId: string,
  ): Promise<AirtableTableSummary[]> {
    const res = await this.fetcher(
      `${AIRTABLE_API_URL}/meta/bases/${encodeURIComponent(baseId)}/tables`,
      { headers: { Authorization: `Bearer ${accessToken}` } },
    );

    if (!res.ok) {
      const text = await res.text();
      throw new Error(`Airtable tables lookup failed (${res.status}): ${text}`);
    }

    const data = (await res.json()) as {
      tables?: Array<{ id?: string; name?: string }>;
    };
    return (data.tables ?? [])
      .filter((t) => t.id && t.name)
      .map((t) => ({ id: t.id as string, name: t.name as string }));
  }
}